### ISSUE TITLE
We get a blank screen after uploading when clicking to use the image or pdf

### ISSUE THREAD

**Issue by mauthitude** [aprokopenko/justcustomfields#15]
We get a blank screen after uploading and when we try and click "select file" the image or pdf in the post.

It worked perfectly before the last wordpress update 3.4.2 and we are using JCFields 1.3 currently... upgrading to the new JCFields a couple weeks ago removed all the posts so i had to revert back to the previous version (1.3)... but currently we get that blank screen when we click "select file"

wordpress 3.4.2
just custom fields 1.3
using our own domain and hosting via godaddy

thanks very much for looking at this... any advice is appreciated :)

**Comment by aprokopenko** [comment]
unable to reproduce with latest wp versions
