### ISSUE TITLE
Simple but useful update to JCF

### ISSUE THREAD

**Issue by jcbenton** [aprokopenko/justcustomfields#48]
I was editing some custom post meta I created and noticed that when I change the slug the values in the wp_postmeta table do not get updated. This leaves orphans and requires me to go back through posts, which creates new post meta. I am not a WP guru, but the WP code equivalent of the below would be helpful.

[Your $_POST trigger]
- A select statement to determine if the custom field is new or one being edited.
- If this is a JCF item being edited, determine the old slug and then ...
  UPDATE wp_postmeta SET meta_key='NEW_SLUG' WHERE meta_key='OLD_SLUG'

I haven't dug through your code yet to find exactly where it goes, but I am assuming you do :)

**Comment by aprokopenko** [comment]
Hi Jerry,

Thanks for your feedback. I know about this problem. This plugin was initially developed for developers inside our company. So in general they know that they can run query to update this. 

We have more priority issues in list right now (we're working on new field type "Collection" to be able to group any other fields into 1 repeatable group).

If you want to help us you can make pull request with this update. The save is processed in main field class:
https://github.com/aprokopenko/justcustomfields/blob/master/inc/class.field.php#L256

**Comment by jcbenton** [comment]
Alex,

Thanks for the reply. I have been doing the same as your devs by running a query. I will take a look at the code and see if I can help. 

-
Jerry Benton
www.mailborder.com
