### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by beepleap** [aprokopenko/justcustomfields#66]
Hi ,sorry I got a dumb newbie question, that is driving me insane. I wanted to do a bulk edit. So, I logged in myphpadmin and looked in the database for the plugin's data to bulk edit, but I can't find it. Can you tell me where the data is stored please

**Comment by aprokopenko** [comment]
Hi,

It uses standard WordPress custom fields functions. So it's stored in
postmeta table in database.

13 окт. 2016 г. 7:46 PM пользователь "beepleap" <notifications@github.com>
написал:

**Comment by beepleap** [comment]
thank you
